module.exports = {

  EXPORT_THEMES_REQUEST: 'EXPORT_THEMES_REQUEST',
  EXPORT_PROGRESS: 'EXPORT_PROGRESS',
  EXPORT_CANCEL: 'EXPORT_CANCEL',
  EXPORT_ERROR: 'EXPORT_ERROR',
  EXPORT_COMPLETE: 'EXPORT_COMPLETE',
  EXPORT_COLORS_REQUEST: 'EXPORT_COLORS_REQUEST',

  SAVE_REQUEST: 'SAVE_REQUEST',
  SAVE_AS_REQUEST: 'SAVE_AS_REQUEST',
  SAVE_COMPLETE: 'SAVE_COMPLETE',
  SAVE_ERRORED: 'SAVE_ERRORED',

};
